-- AlterTable
ALTER TABLE `shop_verifications` MODIFY `section` ENUM('LOCATION', 'OWNER_INFO', 'PHONE', 'CONTACT_INFO', 'IMAGES', 'CATEGORY', 'NAME', 'DAILY_WORKING_HOURS', 'BUSINESS_TYPE', 'INSTAGRAM_USERNAME', 'NATIONAL_CARD', 'ADDRESS_VERIFICATION', 'AUTHENTICATION_VIDEO', 'BUSINESS_LICENSE') NOT NULL;

-- CreateTable
CREATE TABLE `shopDocuments` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `document_url` VARCHAR(191) NOT NULL,
    `section` ENUM('LOCATION', 'OWNER_INFO', 'PHONE', 'CONTACT_INFO', 'IMAGES', 'CATEGORY', 'NAME', 'DAILY_WORKING_HOURS', 'BUSINESS_TYPE', 'INSTAGRAM_USERNAME', 'NATIONAL_CARD', 'ADDRESS_VERIFICATION', 'AUTHENTICATION_VIDEO', 'BUSINESS_LICENSE') NOT NULL,
    `business_license_type` ENUM('NATIONAL_PERMITS_SYSTEM', 'IRANIAN_ASNAF', 'PHARMACY_LICENSE') NULL,
    `shop_id` INTEGER NOT NULL,
    `created_at` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updated_at` TIMESTAMP(0) NOT NULL,

    INDEX `shopDocuments_shop_id_idx`(`shop_id`),
    UNIQUE INDEX `shopDocuments_shop_id_section_key`(`shop_id`, `section`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `shopDocuments` ADD CONSTRAINT `shopDocuments_shop_id_fkey` FOREIGN KEY (`shop_id`) REFERENCES `shops`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
